version: '3.4'

services:
  grafana:
    container_name: grafana
    build:
      context: ./
      dockerfile: Dockerfile
    image: ghcr.io/volkovlabs/balena-app:latest
    entrypoint: /run.sh
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/plugins/volkovlabs-balena-app/dashboards/supervisor.json
      - BALENA_SUPERVISOR_ADDRESS=${BALENA_SUPERVISOR_ADDRESS}
      - BALENA_SUPERVISOR_API_KEY=${BALENA_SUPERVISOR_API_KEY}
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-balena-app
      - ./provisioning:/etc/grafana/provisioning

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    environment:
      - GRAFANA_HOST=host.docker.internal
    ports:
      - 80:80/tcp
      - 443:443/tcp
    depends_on:
      - grafana
