name: Balena Block

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  balena:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Balena Push
        uses: Theia-Scientific/balena-cli@v2
        with:
          balena_api_token: ${{secrets.BALENA_TOKEN}}
          balena_command: "push volkovlabs/balena-app"
